import React, { createContext, useContext, useState } from 'react';

export interface Language {
  code: string;
  name: string;
  flag: string;
  dir?: 'ltr' | 'rtl';
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ta', name: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  { code: 'pt', name: 'Português', flag: '🇧🇷' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'bn', name: 'বাংলা', flag: '🇧🇩' },
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    nav_problem: 'Problem',
    nav_solution: 'Solution',
    nav_scanner: 'AI Scanner',
    nav_how_it_works: 'How It Works',
    nav_features: 'Features',
    nav_architecture: 'Architecture',
    nav_impact: 'Impact',
    nav_roadmap: 'Roadmap',
    nav_team: 'Team',
    nav_demo_btn: 'View Live Demo',
    hero_eyebrow: 'PREDICTIVE URBAN INFRASTRUCTURE MONITORING',
    hero_title1: 'Predict Before',
    hero_title2: 'Disaster.',
    hero_subheadline: 'An AI platform that detects, scores, and predicts infrastructure failures — from a single photo — before they become accidents.',
    hero_cta_how: 'See How It Works',
    hero_cta_map: 'Explore the Health Map',
    scanner_tag: 'HIGH-PRECISION AI VISION ENGINE',
    scanner_title: 'Upload an asset photo.',
    scanner_subtitle: 'AI automatically detects the exact problem.',
    scanner_drop_title: 'Drop your infrastructure asset photo here',
    scanner_drop_desc: 'Upload any photo of a road, bridge, pole, or transformer to execute 100% precision computer vision analysis.',
    scanner_btn_select: 'Select File to Analyze',
    scanner_preset_label: 'Or test sample field inspection cases:',
    scanner_analyzing: 'Running Pixel-Level Neural Analysis...',
    scanner_result_badge: '100% ACCURATE AI DIAGNOSTIC',
    scanner_detected_label: 'AUTOMATICALLY DETECTED PROBLEM',
    scanner_severity: 'SEVERITY SCORE',
    scanner_breakdown: 'PREDICTED BREAKDOWN',
    scanner_action_label: 'RECOMMENDED MUNICIPAL DISPATCH',
    scanner_pin_btn: 'Pin Defect to Health Map',
  },
  es: {
    nav_problem: 'Problema',
    nav_solution: 'Solución',
    nav_scanner: 'Escáner IA',
    nav_how_it_works: 'Cómo Funciona',
    nav_features: 'Funciones',
    nav_architecture: 'Arquitectura',
    nav_impact: 'Impacto',
    nav_roadmap: 'Hoja de Ruta',
    nav_team: 'Equipo',
    nav_demo_btn: 'Ver Demostración',
    hero_eyebrow: 'MONITOREO PREDICTIVO DE INFRAESTRUCTURA URBANA',
    hero_title1: 'Predecir Antes del',
    hero_title2: 'Desastre.',
    hero_subheadline: 'Una plataforma de IA que detecta, califica y predice fallos de infraestructura a partir de una sola foto.',
    hero_cta_how: 'Ver Cómo Funciona',
    hero_cta_map: 'Explorar Mapa de Salud',
    scanner_tag: 'MOTOR DE VISIÓN IA DE ALTA PRECISIÓN',
    scanner_title: 'Sube una foto de infraestructura.',
    scanner_subtitle: 'La IA detecta automáticamente el problema exacto.',
    scanner_drop_title: 'Arrastra aquí la foto de tu infraestructura',
    scanner_drop_desc: 'Sube cualquier foto de carretera, puente o transformador para un análisis de precisión del 100%.',
    scanner_btn_select: 'Seleccionar Archivo',
    scanner_preset_label: 'O prueba casos de muestra:',
    scanner_analyzing: 'Ejecutando Análisis Neuronal...',
    scanner_result_badge: 'DIAGNÓSTICO IA 100% PRECISO',
    scanner_detected_label: 'PROBLEMA DETECTADO AUTOMÁTICAMENTE',
    scanner_severity: 'PUNTUACIÓN DE SEVERIDAD',
    scanner_breakdown: 'FALLO PREVISTO',
    scanner_action_label: 'DESPACHO MUNICIPAL RECOMENDADO',
    scanner_pin_btn: 'Fijar Defecto en Mapa de Salud',
  },
  fr: {
    nav_problem: 'Problème',
    nav_solution: 'Solution',
    nav_scanner: 'Scanner IA',
    nav_how_it_works: 'Fonctionnement',
    nav_features: 'Fonctionnalités',
    nav_architecture: 'Architecture',
    nav_impact: 'Impact',
    nav_roadmap: 'Feuille de Route',
    nav_team: 'Équipe',
    nav_demo_btn: 'Voir la Démo',
    hero_eyebrow: 'SURVEILLANCE PRÉDICTIVE DE L\'INFRASTRUCTURE',
    hero_title1: 'Prédire Avant la',
    hero_title2: 'Catastrophe.',
    hero_subheadline: 'Une plateforme IA qui détecte, évalue et prédit les défaillances d\'infrastructure à partir d\'une seule photo.',
    hero_cta_how: 'Comment Ça Marche',
    hero_cta_map: 'Explorer la Carte',
    scanner_tag: 'MOTEUR DE VISION IA HAUTE PRÉCISION',
    scanner_title: 'Téléchargez une photo d\'infrastructure.',
    scanner_subtitle: 'L\'IA détecte automatiquement le problème exact.',
    scanner_drop_title: 'Déposez votre photo ici',
    scanner_drop_desc: 'Téléchargez une photo de route, pont ou transformateur pour une analyse 100% précise.',
    scanner_btn_select: 'Sélectionner un Fichier',
    scanner_preset_label: 'Ou tester des exemples d\'inspection :',
    scanner_analyzing: 'Analyse Neuronale en Cours...',
    scanner_result_badge: 'DIAGNOSTIC IA 100% PRÉCIS',
    scanner_detected_label: 'PROBLÈME DÉTECTÉ AUTOMATIQUEMENT',
    scanner_severity: 'SCORE DE SÉVÉRITÉ',
    scanner_breakdown: 'PANNE PRÉVUE',
    scanner_action_label: 'INTERVENTION MUNICIPALE RECOMMANDÉE',
    scanner_pin_btn: 'Épingler sur la Carte de Santé',
  },
  de: {
    nav_problem: 'Problem',
    nav_solution: 'Lösung',
    nav_scanner: 'KI Scanner',
    nav_how_it_works: 'Funktionsweise',
    nav_features: 'Funktionen',
    nav_architecture: 'Architektur',
    nav_impact: 'Auswirkung',
    nav_roadmap: 'Roadmap',
    nav_team: 'Team',
    nav_demo_btn: 'Live-Demo Ansehen',
    hero_eyebrow: 'PRÄDIKTIVE INFRASTRUKTUR-ÜBERWACHUNG',
    hero_title1: 'Vorhersagen Vor der',
    hero_title2: 'Katastrophe.',
    hero_subheadline: 'Eine KI-Plattform, die Infrastrukturfehler anhand eines einzigen Fotos erkennt, bewertet und vorhersagt.',
    hero_cta_how: 'Wie Es Funktioniert',
    hero_cta_map: 'Gesundheitskarte Erkunden',
    scanner_tag: 'HOCHPRÄZISION KI-VISION ENGINE',
    scanner_title: 'Laden Sie ein Foto hoch.',
    scanner_subtitle: 'Die KI erkennt das genaue Problem automatisch.',
    scanner_drop_title: 'Ziehen Sie Ihr Foto hierher',
    scanner_drop_desc: 'Laden Sie ein Foto von Straßen, Brücken oder Transformatoren für eine 100% genaue Analyse hoch.',
    scanner_btn_select: 'Datei Auswählen',
    scanner_preset_label: 'Oder testen Sie Beispielfälle:',
    scanner_analyzing: 'Neuronaler Scan Läuft...',
    scanner_result_badge: '100% PRÄZISE KI-DIAGNOSE',
    scanner_detected_label: 'AUTOMATISCH ERKANNTES PROBLEM',
    scanner_severity: 'SCHWEREPUNKT SCORE',
    scanner_breakdown: 'VORHERGESAGTER AUSFALL',
    scanner_action_label: 'EMPFOHLENER MUNICIPAL DISPATCH',
    scanner_pin_btn: 'Defekt Auf Karte Markieren',
  },
  hi: {
    nav_problem: 'समस्या',
    nav_solution: 'समाधान',
    nav_scanner: 'एआई स्कैनर',
    nav_how_it_works: 'यह कैसे काम करता है',
    nav_features: 'विशेषताएं',
    nav_architecture: 'आर्किटेक्चर',
    nav_impact: 'प्रभाव',
    nav_roadmap: 'रोडमैप',
    nav_team: 'टीम',
    nav_demo_btn: 'लाइव डेमो देखें',
    hero_eyebrow: 'पूर्वानुमानित शहरी अवसंरचना निगरानी',
    hero_title1: 'आपदा से पहले',
    hero_title2: 'पूर्वानुमान लगाएं।',
    hero_subheadline: 'एक एआई प्लेटफॉर्म जो केवल एक तस्वीर से बुनियादी ढांचे की विफलताओं का पता लगाता है, स्कोर करता है और भविष्यवाणी करता है।',
    hero_cta_how: 'देखें यह कैसे काम करता है',
    hero_cta_map: 'हेल्थ मैप देखें',
    scanner_tag: 'उच्च-सटीक एआई विज़न इंजन',
    scanner_title: 'एक फोटो अपलोड करें।',
    scanner_subtitle: 'एआई अपने आप सटीक समस्या का पता लगाता है।',
    scanner_drop_title: 'अपनी इंफ्रास्ट्रक्चर फोटो यहां ड्रैग करें',
    scanner_drop_desc: '100% सटीक एआई विश्लेषण के लिए सड़क, पुल या ट्रांसफार्मर की फोटो अपलोड करें।',
    scanner_btn_select: 'फाइल चुनें',
    scanner_preset_label: 'या सैंपल इमेज टेस्ट करें:',
    scanner_analyzing: 'एआई न्यूरल स्कैनिंग जारी है...',
    scanner_result_badge: '100% सटीक एआई निदान',
    scanner_detected_label: 'स्वतः पहचानी गई समस्या',
    scanner_severity: 'गंभीरता स्कोर',
    scanner_breakdown: 'अनुमानित विफलता समय',
    scanner_action_label: 'अनुशंसित नगर निगम कार्रवाई',
    scanner_pin_btn: 'हेल्थ मैप पर पिन करें',
  },
  ta: {
    nav_problem: 'பிரச்சனை',
    nav_solution: 'தீர்வு',
    nav_scanner: 'AI ஸ்கேனர்',
    nav_how_it_works: 'செயல்படும் முறை',
    nav_features: 'அம்சங்கள்',
    nav_architecture: 'கட்டமைப்பு',
    nav_impact: 'தாக்கம்',
    nav_roadmap: 'திட்டம்',
    nav_team: 'குழு',
    nav_demo_btn: 'லைவ் டெமோ பார்க்க',
    hero_eyebrow: 'முன்னறிவிக்கும் நகர்ப்புற உள்கட்டமைப்பு கண்காணிப்பு',
    hero_title1: 'அனர்த்தத்திற்கு முன்பே',
    hero_title2: 'கணிப்போம்.',
    hero_subheadline: 'ஒரே ஒரு புகைப்படத்திலிருந்து உள்கட்டமைப்பு குறைபாடுகளைக் கண்டறிந்து முன்கூட்டியே கணிக்கும் AI தளம்.',
    hero_cta_how: 'செயல்பாட்டைப் பார்க்க',
    hero_cta_map: 'வரைபடத்தை ஆராயுங்கள்',
    scanner_tag: 'உயர் துல்லிய AI விஷன் எஞ்சின்',
    scanner_title: 'புகைப்படத்தைப் பதிவேற்றவும்.',
    scanner_subtitle: 'AI தானாகவே துல்லியமான சிக்கலைக் கண்டறியும்.',
    scanner_drop_title: 'புகைப்படத்தை இங்கே இழுத்து விடுங்கள்',
    scanner_drop_desc: '100% துல்லியமான பகுப்பாய்விற்கு சாலை, பாலம் அல்லது மின்மாற்றி புகைப்படத்தைப் பதிவேற்றவும்.',
    scanner_btn_select: 'கோப்பைத் தேர்ந்தெடுக்கவும்',
    scanner_preset_label: 'அல்லது மாதிரி படங்களைச் சோதிக்கவும்:',
    scanner_analyzing: 'AI நரம்பியல் பகுப்பாய்வு நடக்கிறது...',
    scanner_result_badge: '100% துல்லியமான AI கணிப்பு',
    scanner_detected_label: 'தானாகக் கண்டறியப்பட்ட சிக்கல்',
    scanner_severity: 'பழுதுபார்ப்பு தீவிரம்',
    scanner_breakdown: 'எதிர்பார்க்கப்படும் பழுது நேரம்',
    scanner_action_label: 'பரிந்துரைக்கப்பட்ட நகராட்சி நடவடிக்கை',
    scanner_pin_btn: 'வரைபடத்தில் சேர்க்கவும்',
  },
  te: {
    nav_problem: 'సమస్య',
    nav_solution: 'పరిష్కారం',
    nav_scanner: 'AI స్కానర్',
    nav_how_it_works: 'పనిచేసే విధానం',
    nav_features: 'ఫీచర్లు',
    nav_architecture: 'ఆర్కిటెక్చర్',
    nav_impact: 'ప్రభావం',
    nav_roadmap: 'రోడ్‌మ్యాప్',
    nav_team: 'టీమ్',
    nav_demo_btn: 'లైవ్ డెమో చూడండి',
    hero_eyebrow: 'ముందస్తు మౌలిక సదుపాయాల పర్యవేక్షణ',
    hero_title1: 'ప్రమాదానికి ముందే',
    hero_title2: 'అంచనా వేయండి.',
    hero_subheadline: 'ఒకే ఒక ఫోటో నుండి మౌలిక సదుపాయాల లోపాలను గుర్తించి ముందస్తుగా అంచనా వేసే AI ప్లాట్‌ఫారమ్.',
    hero_cta_how: 'ఇది ఎలా పనిచేస్తుందో చూడండి',
    hero_cta_map: 'హెల్త్ మ్యాప్ చూడండి',
    scanner_tag: 'అత్యంత ఖచ్చితమైన AI విజన్ ఇంజన్',
    scanner_title: 'ఫోటోను అప్‌లోడ్ చేయండి.',
    scanner_subtitle: 'AI ఆటోమేటిక్‌గా సరైన సమస్యను గుర్తిస్తుంది.',
    scanner_drop_title: 'మీ ఫోటోను ఇక్కడ డ్రాగ్ చేయండి',
    scanner_drop_desc: '100% ఖచ్చితమైన విశ్లేషణ కోసం రోడ్డు, వంతెన లేదా ట్రాన్స్‌ఫార్మర్ ఫోటోను అప్‌లోడ్ చేయండి.',
    scanner_btn_select: 'ఫైల్‌ను ఎంచుకోండి',
    scanner_preset_label: 'లేదా శాంపిల్ ఇమేజెస్‌ను టెస్ట్ చేయండి:',
    scanner_analyzing: 'AI న్యూరల్ స్కానింగ్ జరుగుతోంది...',
    scanner_result_badge: '100% ఖచ్చితమైన AI నిర్ధారణ',
    scanner_detected_label: 'ఆటోమేటిక్‌గా గుర్తించిన సమస్య',
    scanner_severity: 'తీవ్రత స్కోరు',
    scanner_breakdown: 'అంచనా వేసిన విచ్ఛిత్తి సమయం',
    scanner_action_label: 'మున్సిపల్ చర్య రికమండేషన్',
    scanner_pin_btn: 'మ్యాప్‌లో పిన్ చేయండి',
  },
  ja: {
    nav_problem: '課題',
    nav_solution: 'ソリューション',
    nav_scanner: 'AIスキャナー',
    nav_how_it_works: '仕組み',
    nav_features: '機能',
    nav_architecture: 'アーキテクチャ',
    nav_impact: '効果',
    nav_roadmap: 'ロードマップ',
    nav_team: 'チーム',
    nav_demo_btn: 'ライブデモを見る',
    hero_eyebrow: '予測型都市インフラモニタリング',
    hero_title1: '災害を事前に',
    hero_title2: '予測する。',
    hero_subheadline: 'たった1枚の写真からインフラの損傷を検出・スコア化し、事故を未然に防ぐAIプラットフォーム。',
    hero_cta_how: '仕組みを見る',
    hero_cta_map: 'ヘルスマップを探索',
    scanner_tag: '高精度AIビジョンエンジン',
    scanner_title: 'インフラ写真をアップロード。',
    scanner_subtitle: 'AIが問題を自動で正確に特定します。',
    scanner_drop_title: 'ここに写真をドロップしてください',
    scanner_drop_desc: '道路、橋、変圧器などの写真をアップロードして100%精度のAI解析を実行。',
    scanner_btn_select: 'ファイルを選択',
    scanner_preset_label: 'またはサンプルケースをテスト:',
    scanner_analyzing: 'AIニューラル解析を実行中...',
    scanner_result_badge: '100%高精度AI診断',
    scanner_detected_label: '自動検出された問題',
    scanner_severity: '重要度スコア',
    scanner_breakdown: '予測破損時期',
    scanner_action_label: '推奨される修繕アクション',
    scanner_pin_btn: 'ヘルスマップに追加',
  },
  zh: {
    nav_problem: '核心痛点',
    nav_solution: '解决方案',
    nav_scanner: 'AI 扫描分析',
    nav_how_it_works: '工作原理',
    nav_features: '功能特点',
    nav_architecture: '技术架构',
    nav_impact: '应用价值',
    nav_roadmap: '发展路线图',
    nav_team: '团队介绍',
    nav_demo_btn: '查看实时演示',
    hero_eyebrow: '预测性城市基础设施监控平台',
    hero_title1: '在灾害发生前',
    hero_title2: '精准预测。',
    hero_subheadline: '仅凭一张照片，AI 即可精准识别、评估并预测城市基础设施隐患，防患于未然。',
    hero_cta_how: '了解工作原理',
    hero_cta_map: '探索城市健康地图',
    scanner_tag: '高精度 AI 视觉引擎',
    scanner_title: '上传设施照片。',
    scanner_subtitle: 'AI 将自动检测并诊断具体隐患。',
    scanner_drop_title: '拖拽照片至此处上传',
    scanner_drop_desc: '上传道路、桥梁或变压器照片，执行 100% 精准度 AI 视觉分析。',
    scanner_btn_select: '选择文件',
    scanner_preset_label: '或测试示例样本：',
    scanner_analyzing: '正在进行 AI 神经网络分析...',
    scanner_result_badge: '100% 精准 AI 诊断结果',
    scanner_detected_label: '自动检测到的具体问题',
    scanner_severity: '严重程度评分',
    scanner_breakdown: '预测损坏时间窗口',
    scanner_action_label: '建议市政处置方案',
    scanner_pin_btn: '标注至健康地图',
  },
  ar: {
    nav_problem: 'المشكلة',
    nav_solution: 'الحل',
    nav_scanner: 'ماسح الذكاء الاصطناعي',
    nav_how_it_works: 'كيف يعمل',
    nav_features: 'الميزات',
    nav_architecture: 'الهندسة المعمارية',
    nav_impact: 'الأثر',
    nav_roadmap: 'خارطة الطريق',
    nav_team: 'الفريق',
    nav_demo_btn: 'عرض التوضيح المباشر',
    hero_eyebrow: 'المراقبة التنبؤية للبنية التحتية للحضر',
    hero_title1: 'التنبؤ قبل',
    hero_title2: 'الكارثة.',
    hero_subheadline: 'منصة ذكاء اصطناعي تكتشف وتقيم وتتنبأ بأعطال البنية التحتية من صورة واحدة.',
    hero_cta_how: 'معرفة كيف يعمل',
    hero_cta_map: 'استكشاف خريطة الصحة',
    scanner_tag: 'محرك الرؤية بالذكاء الاصطناعي عالي الدقة',
    scanner_title: 'قم بتحميل صورة البنية التحتية.',
    scanner_subtitle: 'يكتشف الذكاء الاصطناعي المشكلة بالضبط تلقائيًا.',
    scanner_drop_title: 'اسحب صورة البنية التحتية هنا',
    scanner_drop_desc: 'قم بتحميل صورة للطرق أو الجسور أو المحولات لإجراء تحليل بدقة 100%.',
    scanner_btn_select: 'اختر ملفًا',
    scanner_preset_label: 'أو اختبر عينات التفتيش:',
    scanner_analyzing: 'جاري إجراء التحليل العصبي...',
    scanner_result_badge: 'تشخيص بالذكاء الاصطناعي دقيق بنسبة 100%',
    scanner_detected_label: 'المشكلة المكتشفة تلقائيًا',
    scanner_severity: 'درجة الخطورة',
    scanner_breakdown: 'الزمن المتوقع للفشل',
    scanner_action_label: 'الإجراء البلدي الموصى به',
    scanner_pin_btn: 'تثبيت العيب في خريطة الصحة',
  },
  pt: {
    nav_problem: 'Problema',
    nav_solution: 'Solução',
    nav_scanner: 'Scanner IA',
    nav_how_it_works: 'Como Funciona',
    nav_features: 'Recursos',
    nav_architecture: 'Arquitetura',
    nav_impact: 'Impacto',
    nav_roadmap: 'Roteiro',
    nav_team: 'Equipe',
    nav_demo_btn: 'Ver Demonstração',
    hero_eyebrow: 'MONITORAMENTO PREDITIVO DE INFRAESTRUTURA URBANA',
    hero_title1: 'Prever Antes do',
    hero_title2: 'Desastre.',
    hero_subheadline: 'Uma plataforma de IA que detecta, pontua e prevê falhas de infraestrutura a partir de uma única foto.',
    hero_cta_how: 'Veja Como Funciona',
    hero_cta_map: 'Explorar Mapa de Saúde',
    scanner_tag: 'MOTOR DE VISÃO IA DE ALTA PRECISÃO',
    scanner_title: 'Faça upload de uma foto.',
    scanner_subtitle: 'A IA detecta automaticamente o problema exato.',
    scanner_drop_title: 'Arraste a foto da sua infraestrutura aqui',
    scanner_drop_desc: 'Envie qualquer foto de estrada, ponte ou transformador para análise com 100% de precisão.',
    scanner_btn_select: 'Selecionar Arquivo',
    scanner_preset_label: 'Ou teste casos de exemplo:',
    scanner_analyzing: 'Executando Análise Neural...',
    scanner_result_badge: 'DIAGNÓSTICO DE IA 100% PRECISO',
    scanner_detected_label: 'PROBLEMA DETECTADO AUTOMATICAMENTE',
    scanner_severity: 'PONTUAÇÃO DE SEVERIDADE',
    scanner_breakdown: 'FALHA PREVISTA',
    scanner_action_label: 'AÇÃO MUNICIPAL RECOMENDADA',
    scanner_pin_btn: 'Fixar Defeito no Mapa de Saúde',
  },
  ru: {
    nav_problem: 'Проблема',
    nav_solution: 'Решение',
    nav_scanner: 'ИИ Сканер',
    nav_how_it_works: 'Принцип работы',
    nav_features: 'Возможности',
    nav_architecture: 'Архитектура',
    nav_impact: 'Эффект',
    nav_roadmap: 'Дорожная карта',
    nav_team: 'Команда',
    nav_demo_btn: 'Смотреть Демо',
    hero_eyebrow: 'ПРЕДИКТИВНЫЙ МОНИТОРИНГ ГОРОДСКОЙ ИНФРАСТРУКТУРЫ',
    hero_title1: 'Предсказать До',
    hero_title2: 'Катастрофы.',
    hero_subheadline: 'ИИ-платформа, которая обнаруживает, оценивает и прогнозирует сбои инфраструктуры по одному фото.',
    hero_cta_how: 'Как это работает',
    hero_cta_map: 'Открыть карту состояния',
    scanner_tag: 'ВЫСОКОТОЧНЫЙ ИИ-ДВИЖОК ЗРЕНИЯ',
    scanner_title: 'Загрузите фото объекта.',
    scanner_subtitle: 'ИИ автоматически определит точную проблему.',
    scanner_drop_title: 'Перетащите сюда фото объекта',
    scanner_drop_desc: 'Загрузите фото дороги, моста или трансформатора для 100% точного анализа.',
    scanner_btn_select: 'Выбрать файл',
    scanner_preset_label: 'Или протестируйте образцы:',
    scanner_analyzing: 'Запуск нейронного анализа...',
    scanner_result_badge: '100% ТОЧНАЯ ИИ-ДИАГНОСТИКА',
    scanner_detected_label: 'АВТОМАТИЧЕСКИ ОБНАРУЖЕННАЯ ПРОБЛЕМА',
    scanner_severity: 'ОЦЕНКА СЕРЬЕЗНОСТИ',
    scanner_breakdown: 'ПРОГНОЗИРУЕМЫЙ СБОЙ',
    scanner_action_label: 'РЕКОМЕНДУЕМЫЕ МУНИЦИПАЛЬНЫЕ ДЕЙСТВИЯ',
    scanner_pin_btn: 'Добавить на карту состояния',
  },
  it: {
    nav_problem: 'Problema',
    nav_solution: 'Soluzione',
    nav_scanner: 'Scanner IA',
    nav_how_it_works: 'Come Funziona',
    nav_features: 'Caratteristiche',
    nav_architecture: 'Architettura',
    nav_impact: 'Impatto',
    nav_roadmap: 'Tabella di Marcia',
    nav_team: 'Team',
    nav_demo_btn: 'Vedi Demo Live',
    hero_eyebrow: 'MONITORAGGIO PREDIATTIVO DELLE INFRASTRUTTURE URBANE',
    hero_title1: 'Prevedere Prima del',
    hero_title2: 'Disastro.',
    hero_subheadline: 'Una piattaforma di IA che rileva, valuta e prevede i guasti alle infrastrutture da una singola foto.',
    hero_cta_how: 'Scopri Come Funziona',
    hero_cta_map: 'Esplora la Mappa',
    scanner_tag: 'MOTORE DI VISIONE IA AD ALTA PRECISIONE',
    scanner_title: 'Carica una foto dell\'infrastruttura.',
    scanner_subtitle: 'L\'IA rileva automaticamente il problema esatto.',
    scanner_drop_title: 'Trascina qui la foto dell\'infrastruttura',
    scanner_drop_desc: 'Carica qualsiasi foto di strada, ponte o trasformatore per un\'analisi precisa al 100%.',
    scanner_btn_select: 'Seleziona File',
    scanner_preset_label: 'Oppure testa casi di esempio:',
    scanner_analyzing: 'Analisi Neurale in Corso...',
    scanner_result_badge: 'DIAGNOSI IA PRECISA AL 100%',
    scanner_detected_label: 'PROBLEMA RILEVATO AUTOMATICAMENTE',
    scanner_severity: 'PUNTEGGIO DI GRAVITÀ',
    scanner_breakdown: 'GUASTO PREVISTO',
    scanner_action_label: 'AZIONATO MUNICIPALE RACCOMANDATO',
    scanner_pin_btn: 'Aggiungi Difetto Alla Mappa',
  },
  ko: {
    nav_problem: '문제점',
    nav_solution: '솔루션',
    nav_scanner: 'AI 스캐너',
    nav_how_it_works: '작동 방식',
    nav_features: '주요 기능',
    nav_architecture: '아키텍처',
    nav_impact: '기대 효과',
    nav_roadmap: '로드맵',
    nav_team: '팀 소개',
    nav_demo_btn: '라이브 데모 보기',
    hero_eyebrow: '예측형 도시 인프라 모니터링',
    hero_title1: '재난이 발생하기 전에',
    hero_title2: '예측합니다.',
    hero_subheadline: '단 한 장의 사진으로 인프라 결함을 감지, 평가 및 예측하여 사고를 예방하는 AI 플랫폼.',
    hero_cta_how: '작동 방식 보기',
    hero_cta_map: '헬스 맵 탐색',
    scanner_tag: '고정밀 AI 비전 엔진',
    scanner_title: '인프라 사진을 업로드하세요.',
    scanner_subtitle: 'AI가 정확한 문제를 자동으로 진단합니다.',
    scanner_drop_title: '여기에 사진을 드래그하세요',
    scanner_drop_desc: '도로, 교량, 변압기 사진을 업로드하여 100% 정밀도의 AI 분석을 실행하세요.',
    scanner_btn_select: '파일 선택',
    scanner_preset_label: '또는 샘플 케이스 테스트:',
    scanner_analyzing: 'AI 신경망 분석 실행 중...',
    scanner_result_badge: '100% 정확한 AI 진단',
    scanner_detected_label: '자동 감지된 정확한 문제',
    scanner_severity: '심각도 점수',
    scanner_breakdown: '예상 붕괴 시점',
    scanner_action_label: '권장 지자체 조치 사항',
    scanner_pin_btn: '헬스 맵에 핀 추가',
  },
  bn: {
    nav_problem: 'সমস্যা',
    nav_solution: 'সমাধান',
    nav_scanner: 'এআই স্ক্যানার',
    nav_how_it_works: 'কাজের প্রক্রিয়া',
    nav_features: 'বৈশিষ্ট্য',
    nav_architecture: 'আর্কিটেকচার',
    nav_impact: 'প্রভাব',
    nav_roadmap: 'রোডম্যাপ',
    nav_team: 'টিম',
    nav_demo_btn: 'লাইভ ডেমো দেখুন',
    hero_eyebrow: 'পূর্বানুমান ভিত্তিক নগর পরিকাঠামো পর্যবেক্ষণ',
    hero_title1: 'বিপর্যয়ের আগেই',
    hero_title2: 'পূর্বানুমান করুন।',
    hero_subheadline: 'একটি ছবি থেকেই অবকাঠামোগত ত্রুটি সনাক্তকরণ ও পূর্বানুমান করার এআই প্ল্যাটফর্ম।',
    hero_cta_how: 'কাজের পদ্ধতি দেখুন',
    hero_cta_map: 'হেলথ ম্যাপ দেখুন',
    scanner_tag: 'উচ্চ-সঠিক এআই ভিশন ইঞ্জিন',
    scanner_title: 'ছবি আপলোড করুন।',
    scanner_subtitle: 'এআই স্বয়ংক্রিয়ভাবে সঠিক সমস্যা সনাক্ত করবে।',
    scanner_drop_title: 'আপনার ছবি এখানে ড্র্যাগ করুন',
    scanner_drop_desc: '১০০% সঠিক এআই বিশ্লেষণের জন্য রাস্তা, সেতু বা ট্রান্সফরমারের ছবি আপলোড করুন।',
    scanner_btn_select: 'ফাইল সিলেক্ট করুন',
    scanner_preset_label: 'অথবা নমুনা ছবি পরীক্ষা করুন:',
    scanner_analyzing: 'এআই নিউরাল স্ক্যানিং চলছে...',
    scanner_result_badge: '১০০% সঠিক এআই ডায়াগনস্টিক',
    scanner_detected_label: 'স্বয়ংক্রিয়ভাবে চিহ্নিত সমস্যা',
    scanner_severity: 'তীব্রতার স্কোর',
    scanner_breakdown: 'আনুমানিক ভাঙ্গনের সময়',
    scanner_action_label: 'পৌরসভার পদক্ষেপের সুপারিশ',
    scanner_pin_btn: 'হেলথ ম্যাপে যুক্ত করুন',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(SUPPORTED_LANGUAGES[0]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (lang.dir === 'rtl') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
  };

  const t = (key: string): string => {
    const langDict = TRANSLATIONS[language.code] || TRANSLATIONS['en'];
    return langDict[key] || TRANSLATIONS['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
