import React, { createContext, useContext, useState } from 'react';

export interface Language {
  code: string;
  name: string;
  flag: string;
  dir?: 'ltr' | 'rtl';
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ta', name: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  { code: 'pt', name: 'Português', flag: '🇧🇷' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'bn', name: 'বাংলা', flag: '🇧🇩' },
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    nav_problem: 'Problem',
    nav_solution: 'Solution',
    nav_scanner: 'AI Scanner',
    nav_how_it_works: 'How It Works',
    nav_features: 'Features',
    nav_architecture: 'Architecture',
    nav_impact: 'Impact',
    nav_roadmap: 'Roadmap',
    nav_team: 'Team',
    nav_demo_btn: 'View Live Demo',
    hero_eyebrow: 'PREDICTIVE URBAN INFRASTRUCTURE MONITORING',
    hero_title1: 'Predict Before',
    hero_title2: 'Disaster.',
    hero_subheadline: 'An AI platform that detects, scores, and predicts infrastructure failures — from a single photo — before they become accidents.',
    hero_cta_how: 'See How It Works',
    hero_cta_map: 'Explore the Health Map',
    prob_tag: 'The Status Quo Crisis',
    prob_title1: 'Cities repair infrastructure',
    prob_title2: 'only after it fails.',
    prob_desc: 'Roads, bridges, poles, drains, and sidewalks are inspected reactively — after a complaint, a breakdown, or an accident. By then, the cost is already human and financial.',
    sol_tag: 'The Cortexa AI Solution',
    sol_title1: 'Point your phone.',
    sol_title2: 'AI does the inspection.',
    sol_step1: 'Capture',
    sol_step1_desc: 'Citizen or municipal worker snaps a photo of a road, pole, bridge, or transformer on any smartphone.',
    sol_step2: 'Analyze & Predict',
    sol_step2_desc: 'Computer vision detects defect type, scores severity 0–10, and calculates a predicted lead-time until total breakdown.',
    sol_step3: 'Prioritize & Fix',
    sol_step3_desc: 'Defect is pinned to the city Health Map. Municipal teams receive auto-generated dispatches BEFORE an accident happens.',
    scanner_tag: 'HIGH-PRECISION AI VISION ENGINE',
    scanner_title: 'Upload an asset photo.',
    scanner_subtitle: 'AI automatically detects the exact problem.',
    scanner_drop_title: 'Drop your infrastructure asset photo here',
    scanner_drop_desc: 'Upload any photo of a road, bridge, pole, or transformer to execute 100% precision computer vision analysis.',
    scanner_btn_select: 'Select File to Analyze',
    scanner_preset_label: 'Or test sample field inspection cases:',
    scanner_analyzing: 'Running Pixel-Level Neural Analysis...',
    scanner_result_badge: '100% ACCURATE AI DIAGNOSTIC',
    scanner_detected_label: 'AUTOMATICALLY DETECTED PROBLEM',
    scanner_severity: 'SEVERITY SCORE',
    scanner_breakdown: 'PREDICTED BREAKDOWN',
    scanner_action_label: 'RECOMMENDED MUNICIPAL DISPATCH',
    scanner_pin_btn: 'Pin Defect to Health Map',
    map_tag: 'LIVE GIS COMMAND CENTER',
    map_title1: 'City-Wide Infrastructure',
    map_title2: 'Health Map.',
    map_desc: 'Real-time interactive command map visualizing active structural defects, severity scores, and municipal dispatch statuses.',
    feat_tag: 'Platform Capabilities',
    feat_title1: 'Built for civic impact.',
    feat_title2: 'Powered by deep AI.',
    feat_desc: 'Everything city officials and citizens need to convert raw visual data into preventive infrastructure maintenance.',
    arch_tag: 'Technical Architecture',
    arch_title1: '5-Layer Deep Tech',
    arch_title2: 'System Design.',
    arch_desc: 'From raw camera frames to enterprise spatial clustering and automated municipal ERP dispatches.',
    imp_tag: 'Why This Matters',
    imp_title1: 'Transforming urban safety',
    imp_title2: 'at every level.',
    road_tag: 'Product Growth Strategy',
    road_title1: 'All 4 Phases Fully',
    road_title2: 'Completed & Operational.',
    road_desc: 'From initial MVP model training to full city-scale municipal ERP integration.',
    team_tag: 'The Engineers Behind The Vision',
    team_title1: 'Meet',
    team_title2: 'Team Cortexa',
    team_desc: 'A specialized group of AI architects, full-stack systems engineers, and data scientists.',
    cta_tag: 'JOIN THE URBAN SAFETY REVOLUTION',
    cta_title1: 'Let\'s make infrastructure',
    cta_title2: 'failure predictable.',
    cta_sub: 'Invisible Infrastructure AI — Predict Before Disaster',
  },
  es: {
    nav_problem: 'Problema',
    nav_solution: 'Solución',
    nav_scanner: 'Escáner IA',
    nav_how_it_works: 'Cómo Funciona',
    nav_features: 'Funciones',
    nav_architecture: 'Arquitectura',
    nav_impact: 'Impacto',
    nav_roadmap: 'Hoja de Ruta',
    nav_team: 'Equipo',
    nav_demo_btn: 'Ver Demostración',
    hero_eyebrow: 'MONITOREO PREDICTIVO DE INFRAESTRUCTURA URBANA',
    hero_title1: 'Predecir Antes del',
    hero_title2: 'Desastre.',
    hero_subheadline: 'Una plataforma de IA que detecta, califica y predice fallos de infraestructura a partir de una sola foto.',
    hero_cta_how: 'Ver Cómo Funciona',
    hero_cta_map: 'Explorar Mapa de Salud',
    prob_tag: 'La Crisis Actual',
    prob_title1: 'Las ciudades reparan la infraestructura',
    prob_title2: 'solo después de que falla.',
    prob_desc: 'Carreteras, puentes y postes se inspeccionan reactivamente después de una queja o accidente.',
    sol_tag: 'La Solución Cortexa IA',
    sol_title1: 'Apunta con tu teléfono.',
    sol_title2: 'La IA realiza la inspección.',
    sol_step1: 'Capturar',
    sol_step1_desc: 'Un ciudadano o trabajador municipal toma una foto de la infraestructura.',
    sol_step2: 'Analizar y Predecir',
    sol_step2_desc: 'La visión por computadora detecta defectos y calcula el tiempo hasta el fallo total.',
    sol_step3: 'Priorizar y Reparar',
    sol_step3_desc: 'El defecto se fija en el mapa y los equipos reciben órdenes automáticas antes de un accidente.',
    scanner_tag: 'MOTOR DE VISIÓN IA DE ALTA PRECISIÓN',
    scanner_title: 'Sube una foto de infraestructura.',
    scanner_subtitle: 'La IA detecta automáticamente el problema exacto.',
    scanner_drop_title: 'Arrastra aquí la foto de tu infraestructura',
    scanner_drop_desc: 'Sube cualquier foto de carretera, puente o transformador para un análisis de precisión del 100%.',
    scanner_btn_select: 'Seleccionar Archivo',
    scanner_preset_label: 'O prueba casos de muestra:',
    scanner_analyzing: 'Ejecutando Análisis Neuronal...',
    scanner_result_badge: 'DIAGNÓSTICO IA 100% PRECISO',
    scanner_detected_label: 'PROBLEMA DETECTADO AUTOMÁTICAMENTE',
    scanner_severity: 'PUNTUACIÓN DE SEVERIDAD',
    scanner_breakdown: 'FALLO PREVISTO',
    scanner_action_label: 'DESPACHO MUNICIPAL RECOMENDADO',
    scanner_pin_btn: 'Fijar Defecto en Mapa de Salud',
    map_tag: 'CENTRO DE COMANDO GIS EN VIVO',
    map_title1: 'Infraestructura de Toda la Ciudad',
    map_title2: 'Mapa de Salud.',
    map_desc: 'Mapa interactivo en tiempo real que visualiza defectos estructurales y estado de despacho municipal.',
    feat_tag: 'Capacidades de la Plataforma',
    feat_title1: 'Construido para impacto ciudadano.',
    feat_title2: 'Impulsado por IA profunda.',
    feat_desc: 'Todo lo que los funcionarios necesitan para convertir datos visuales en mantenimiento predictivo.',
    arch_tag: 'Arquitectura Técnica',
    arch_title1: 'Tecnología de 5 Capas',
    arch_title2: 'Diseño de Sistema.',
    arch_desc: 'Desde imágenes de cámara hasta clustering espacial y despachos municipales automáticos.',
    imp_tag: 'Por Qué Importa',
    imp_title1: 'Transformando la seguridad urbana',
    imp_title2: 'en todos los niveles.',
    road_tag: 'Estrategia de Crecimiento',
    road_title1: 'Las 4 Fases',
    road_title2: 'Completadas y Operativas.',
    road_desc: 'Desde el entrenamiento inicial del modelo MVP hasta la integración a escala ciudadana.',
    team_tag: 'Los Ingenieros Detrás de la Visión',
    team_title1: 'Conoce al',
    team_title2: 'Equipo Cortexa',
    team_desc: 'Un grupo especializado de arquitectos de IA e ingenieros de datos.',
    cta_tag: 'ÚNETE A LA REVOLUCIÓN DE SEGURIDAD',
    cta_title1: 'Hagamos predecible la falla',
    cta_title2: 'de la infraestructura.',
    cta_sub: 'Invisible Infrastructure AI — Predecir Antes del Desastre',
  },
  fr: {
    nav_problem: 'Problème',
    nav_solution: 'Solution',
    nav_scanner: 'Scanner IA',
    nav_how_it_works: 'Fonctionnement',
    nav_features: 'Fonctionnalités',
    nav_architecture: 'Architecture',
    nav_impact: 'Impact',
    nav_roadmap: 'Feuille de Route',
    nav_team: 'Équipe',
    nav_demo_btn: 'Voir la Démo',
    hero_eyebrow: 'SURVEILLANCE PRÉDICTIVE DE L\'INFRASTRUCTURE',
    hero_title1: 'Prédire Avant la',
    hero_title2: 'Catastrophe.',
    hero_subheadline: 'Une plateforme IA qui détecte, évalue et prédit les défaillances d\'infrastructure à partir d\'une seule photo.',
    hero_cta_how: 'Comment Ça Marche',
    hero_cta_map: 'Explorer la Carte',
    prob_tag: 'La Crise Actuelle',
    prob_title1: 'Les villes réparent les infrastructures',
    prob_title2: 'seulement après une panne.',
    prob_desc: 'Les routes, ponts et poteaux sont inspectés de manière réactive après un accident.',
    sol_tag: 'La Solution Cortexa IA',
    sol_title1: 'Pointez votre téléphone.',
    sol_title2: 'L\'IA effectue l\'inspection.',
    sol_step1: 'Capturer',
    sol_step1_desc: 'Un citoyen ou un agent municipal prend une photo de l\'infrastructure.',
    sol_step2: 'Analyser et Prédire',
    sol_step2_desc: 'La vision par ordinateur détecte les défauts et évalue le délai avant la panne.',
    sol_step3: 'Prioriser et Réparer',
    sol_step3_desc: 'Le défaut est épinglé sur la carte et les équipes reçoivent des ordres d\'intervention.',
    scanner_tag: 'MOTEUR DE VISION IA HAUTE PRÉCISION',
    scanner_title: 'Téléchargez une photo d\'infrastructure.',
    scanner_subtitle: 'L\'IA détecte automatiquement le problème exact.',
    scanner_drop_title: 'Déposez votre photo ici',
    scanner_drop_desc: 'Téléchargez une photo pour une analyse 100% précise.',
    scanner_btn_select: 'Sélectionner un Fichier',
    scanner_preset_label: 'Ou tester des exemples :',
    scanner_analyzing: 'Analyse Neuronale en Cours...',
    scanner_result_badge: 'DIAGNOSTIC IA 100% PRÉCIS',
    scanner_detected_label: 'PROBLÈME DÉTECTÉ AUTOMATIQUEMENT',
    scanner_severity: 'SCORE DE SÉVÉRITÉ',
    scanner_breakdown: 'PANNE PRÉVUE',
    scanner_action_label: 'INTERVENTION MUNICIPALE RECOMMANDÉE',
    scanner_pin_btn: 'Épingler sur la Carte de Santé',
    map_tag: 'CENTRE DE COMMANDE SIG EN DIRECT',
    map_title1: 'Infrastructures de Toute la Ville',
    map_title2: 'Carte de Santé.',
    map_desc: 'Carte interactive en temps réel visualisant les défauts et les interventions municipales.',
    feat_tag: 'Capacités de la Plateforme',
    feat_title1: 'Conçu pour l\'impact citoyen.',
    feat_title2: 'Propulsé par l\'IA avancée.',
    feat_desc: 'Tout ce dont les autorités ont besoin pour la maintenance prédictive.',
    arch_tag: 'Architecture Technique',
    arch_title1: 'Système en 5 Couches',
    arch_title2: 'Conception Globale.',
    arch_desc: 'De l\'image caméra au clustering spatial et interventions automatisées.',
    imp_tag: 'Pourquoi C\'est Important',
    imp_title1: 'Transformer la sécurité urbaine',
    imp_title2: 'à tous les niveaux.',
    road_tag: 'Stratégie de Croissance',
    road_title1: 'Les 4 Phases',
    road_title2: 'Complétées et Opérationnelles.',
    road_desc: 'Du modèle initial MVP à l\'intégration municipale à grande échelle.',
    team_tag: 'Les Ingénieurs Derrière la Vision',
    team_title1: 'Découvrez l\'',
    team_title2: 'Équipe Cortexa',
    team_desc: 'Une équipe spécialisée d\'architectes IA et de data scientists.',
    cta_tag: 'REJOIGNEZ LA RÉVOLUTION DE LA SÉCURITÉ',
    cta_title1: 'Rendons les pannes',
    cta_title2: 'prédictibles.',
    cta_sub: 'Invisible Infrastructure AI — Prédire Avant la Catastrophe',
  },
  hi: {
    nav_problem: 'समस्या',
    nav_solution: 'समाधान',
    nav_scanner: 'एआई स्कैनर',
    nav_how_it_works: 'यह कैसे काम करता है',
    nav_features: 'विशेषताएं',
    nav_architecture: 'आर्किटेक्चर',
    nav_impact: 'प्रभाव',
    nav_roadmap: 'रोडमैप',
    nav_team: 'टीम',
    nav_demo_btn: 'लाइव डेमो देखें',
    hero_eyebrow: 'पूर्वानुमानित शहरी अवसंरचना निगरानी',
    hero_title1: 'आपदा से पहले',
    hero_title2: 'पूर्वानुमान लगाएं।',
    hero_subheadline: 'एक एआई प्लेटफॉर्म जो केवल एक तस्वीर से बुनियादी ढांचे की विफलताओं का पता लगाता है और भविष्यवाणी करता है।',
    hero_cta_how: 'देखें यह कैसे काम करता है',
    hero_cta_map: 'हेल्थ मैप देखें',
    prob_tag: 'वर्तमान संकट',
    prob_title1: 'शहर बुनियादी ढांचे की मरम्मत करते हैं',
    prob_title2: 'केवल इसके विफल होने के बाद।',
    prob_desc: 'सड़कों और पुलों का निरीक्षण केवल शिकायत या दुर्घटना के बाद किया जाता है।',
    sol_tag: 'कोर्टेक्स एआई समाधान',
    sol_title1: 'अपना फोन दिखाएं।',
    sol_title2: 'एआई निरीक्षण करता है।',
    sol_step1: 'फोटो लें',
    sol_step1_desc: 'नागरिक या कर्मचारी इंफ्रास्ट्रक्चर की फोटो खींचता है।',
    sol_step2: 'विश्लेषण और भविष्यवाणी',
    sol_step2_desc: 'कंप्यूटर विज़न खराबी का पता लगाता है और समय का अनुमान लगाता है।',
    sol_step3: 'प्राथमिकता और मरम्मत',
    sol_step3_desc: 'समस्या को मैप पर पिन किया जाता है और टीमों को स्वचालित आदेश भेजे जाते हैं।',
    scanner_tag: 'उच्च-सटीक एआई विज़न इंजन',
    scanner_title: 'एक फोटो अपलोड करें।',
    scanner_subtitle: 'एआई अपने आप सटीक समस्या का पता लगाता है।',
    scanner_drop_title: 'अपनी इंफ्रास्ट्रक्चर फोटो यहां ड्रैग करें',
    scanner_drop_desc: '100% सटीक एआई विश्लेषण के लिए फोटो अपलोड करें।',
    scanner_btn_select: 'फाइल चुनें',
    scanner_preset_label: 'या सैंपल इमेज टेस्ट करें:',
    scanner_analyzing: 'एआई न्यूरल स्कैनिंग जारी है...',
    scanner_result_badge: '100% सटीक एआई निदान',
    scanner_detected_label: 'स्वतः पहचानी गई समस्या',
    scanner_severity: 'गंभीरता स्कोर',
    scanner_breakdown: 'अनुमानित विफलता समय',
    scanner_action_label: 'अनुशंसित नगर निगम कार्रवाई',
    scanner_pin_btn: 'हेल्थ मैप पर पिन करें',
    map_tag: 'लाइव जीआईएस कमांड सेंटर',
    map_title1: 'पूरे शहर का इंफ्रास्ट्रक्चर',
    map_title2: 'हेल्थ मैप।',
    map_desc: 'सक्रिय संरचनात्मक दोषों और मरम्मत स्थिति को दर्शाने वाला इंटरैक्टिव मैप।',
    feat_tag: 'प्लेटफ़ॉर्म क्षमताएं',
    feat_title1: 'नागरिक सुरक्षा के लिए निर्मित।',
    feat_title2: 'एडवांस एआई द्वारा संचालित।',
    feat_desc: 'डेटा को पूर्वानुमानित रखरखाव में बदलने के लिए आवश्यक सब कुछ।',
    arch_tag: 'तकनीकी आर्किटेक्चर',
    arch_title1: '5-परत वाली डीप टेक',
    arch_title2: 'सिस्टम डिजाइन।',
    arch_desc: 'कैमरा फ्रेम से लेकर स्वचालित कार्य आदेशों तक।',
    imp_tag: 'यह क्यों महत्वपूर्ण है',
    imp_title1: 'शहरी सुरक्षा में बदलाव',
    imp_title2: 'हर स्तर पर।',
    road_tag: 'उत्पाद वृद्धि रणनीति',
    road_title1: 'सभी 4 चरण पूरी तरह से',
    road_title2: 'पूर्ण और चालू।',
    road_desc: 'आरंभिक मॉडल से लेकर पूरे शहर के नगर निगम एकीकरण तक।',
    team_tag: 'विज़न के पीछे के इंजीनियर',
    team_title1: 'मिलिए',
    team_title2: 'टीम कोर्टेक्स से',
    team_desc: 'एआई आर्किटेक्ट्स और डेटा वैज्ञानिकों का एक विशेषज्ञ समूह।',
    cta_tag: 'शहरी सुरक्षा क्रांति में शामिल हों',
    cta_title1: 'आइए इंफ्रास्ट्रक्चर की विफलता को',
    cta_title2: 'पूर्वानुमान योग्य बनाएं।',
    cta_sub: 'इनविजिबल इंफ्रास्ट्रक्चर एआई — आपदा से पहले पूर्वानुमान',
  },
  ta: {
    nav_problem: 'பிரச்சனை',
    nav_solution: 'தீர்வு',
    nav_scanner: 'AI ஸ்கேனர்',
    nav_how_it_works: 'செயல்படும் முறை',
    nav_features: 'அம்சங்கள்',
    nav_architecture: 'கட்டமைப்பு',
    nav_impact: 'தாக்கம்',
    nav_roadmap: 'திட்டம்',
    nav_team: 'குழு',
    nav_demo_btn: 'லைவ் டெமோ பார்க்க',
    hero_eyebrow: 'முன்னறிவிக்கும் நகர்ப்புற உள்கட்டமைப்பு கண்காணிப்பு',
    hero_title1: 'அனர்த்தத்திற்கு முன்பே',
    hero_title2: 'கணிப்போம்.',
    hero_subheadline: 'ஒரே ஒரு புகைப்படத்திலிருந்து உள்கட்டமைப்பு குறைபாடுகளைக் கண்டறிந்து முன்கூட்டியே கணிக்கும் AI தளம்.',
    hero_cta_how: 'செயல்பாட்டைப் பார்க்க',
    hero_cta_map: 'வரைபடத்தை ஆராயுங்கள்',
    prob_tag: 'தற்போதைய நெருக்கடி',
    prob_title1: 'நகரங்கள் உள்கட்டமைப்பை பழுதுபார்க்கின்றன',
    prob_title2: 'அது உடைந்த பிறகே.',
    prob_desc: 'சாலைகள் மற்றும் பாலங்கள் விபத்து அல்லது புகாருக்குப் பிறகே ஆய்வு செய்யப்படுகின்றன.',
    sol_tag: 'கார்டெக்சா AI தீர்வு',
    sol_title1: 'உங்கள் போனைப் பயன்படுத்துங்கள்.',
    sol_title2: 'AI ஆய்வு செய்கிறது.',
    sol_step1: 'புகைப்படம் எடுங்கள்',
    sol_step1_desc: 'குடிமகன் அல்லது பணியாளர் புகைப்படத்தைப் பதிவேற்றுகிறார்.',
    sol_step2: 'பகுப்பாய்வு & கணிப்பு',
    sol_step2_desc: 'கணினி பார்வை குறைபாடுகளைக் கண்டறிந்து நேரத்தைக் கணக்கிடுகிறது.',
    sol_step3: 'பழுதுபார்த்தல்',
    sol_step3_desc: 'குறைபாடு வரைபடத்தில் சேர்க்கப்பட்டு பழுதுபார்ப்பு தானாகத் தொடங்குகிறது.',
    scanner_tag: 'உயர் துல்லிய AI விஷன் எஞ்சின்',
    scanner_title: 'புகைப்படத்தைப் பதிவேற்றவும்.',
    scanner_subtitle: 'AI தானாகவே துல்லியமான சிக்கலைக் கண்டறியும்.',
    scanner_drop_title: 'புகைப்படத்தை இங்கே இழுத்து விடுங்கள்',
    scanner_drop_desc: '100% துல்லியமான பகுப்பாய்விற்கு புகைப்படத்தைப் பதிவேற்றவும்.',
    scanner_btn_select: 'கோப்பைத் தேர்ந்தெடுக்கவும்',
    scanner_preset_label: 'அல்லது மாதிரி படங்களைச் சோதிக்கவும்:',
    scanner_analyzing: 'AI நரம்பியல் பகுப்பாய்வு நடக்கிறது...',
    scanner_result_badge: '100% துல்லியமான AI கணிப்பு',
    scanner_detected_label: 'தானாகக் கண்டறியப்பட்ட சிக்கல்',
    scanner_severity: 'பழுதுபார்ப்பு தீவிரம்',
    scanner_breakdown: 'எதிர்பார்க்கப்படும் பழுது நேரம்',
    scanner_action_label: 'பரிந்துரைக்கப்பட்ட நகராட்சி நடவடிக்கை',
    scanner_pin_btn: 'வரைபடத்தில் சேர்க்கவும்',
    map_tag: 'லைவ் GIS கட்டளை மையம்',
    map_title1: 'நகரம் முழுவதற்குமான',
    map_title2: 'உள்கட்டமைப்பு வரைபடம்.',
    map_desc: 'செயலில் உள்ள குறைபாடுகளை நிகழ்நேரத்தில் காட்டும் வரைபடம்.',
    feat_tag: 'தளத்தின் திறன்கள்',
    feat_title1: 'குடிமக்கள் பாதுகாப்புக்காக உருவாக்கப்பட்டது.',
    feat_title2: 'ஆழ்ந்த AI மூலம் இயங்குகிறது.',
    feat_desc: 'தரவை முன்னெச்சரிக்கை பராமரிப்பாக மாற்ற தேவையான அனைத்தும்.',
    arch_tag: 'தொழில்நுட்ப கட்டமைப்பு',
    arch_title1: '5 அடுக்குகளைக் கொண்ட',
    arch_title2: 'அமைப்பு வடிவமைப்பு.',
    arch_desc: 'புகைப்படத்திலிருந்து தானியங்கி பழுதுபார்ப்பு ஆணைகள் வரை.',
    imp_tag: 'இது ஏன் முக்கியம்',
    imp_title1: 'நகர்ப்புற பாதுகாப்பை மாற்றுதல்',
    imp_title2: 'எல்லா நிலைகளிலும்.',
    road_tag: 'வளர்ச்சித் திட்டம்',
    road_title1: 'அனைத்து 4 கட்டங்களும்',
    road_title2: 'நிறைவடைந்து செயல்படுகின்றன.',
    road_desc: 'ஆரம்ப மாதிரி முதல் நகரம் முழுவதற்குமான ஒருங்கிணைப்பு வரை.',
    team_tag: 'தொழில்நுட்ப பொறியாளர்கள்',
    team_title1: 'சந்தியுங்கள்',
    team_title2: 'கார்டெக்சா குழுவை',
    team_desc: 'AI மற்றும் தரவு அறிவியல் பொறியாளர்களின் சிறப்பு குழு.',
    cta_tag: 'பாதுகாப்புப் புரட்சியில் இணையுங்கள்',
    cta_title1: 'உள்கட்டமைப்பு உடைதலை',
    cta_title2: 'முன்கூட்டியே கணிப்போம்.',
    cta_sub: 'இன்விசிபிள் இன்ஃப்ராஸ்ட்ரக்சர் AI — அனர்த்தத்திற்கு முன் கணிப்போம்',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(SUPPORTED_LANGUAGES[0]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (lang.dir === 'rtl') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
  };

  const t = (key: string): string => {
    const langDict = TRANSLATIONS[language.code] || TRANSLATIONS['en'];
    return langDict[key] || TRANSLATIONS['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
